/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GDCN.DichVu;

import Dao.dao.LoaiPhongDao;
import Dao.dao.NguoiDungDao;
import Dao.dao.PhongDao;
import Dao.daoimpl.LoaiPhongDaoImpl;
import Dao.daoimpl.NguoiDungDaoImpl;
import Dao.daoimpl.PhongDaoImpl;
import Dao.entity.LoaiPhong;
import Dao.entity.NguoiDung;
import Dao.entity.Phong;
import GDCN.TiepTan.TrangChu;
import Util.XAuth;
import Util.XDialog;
import Util.XIcon;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.io.File;
import java.util.List;
import java.util.function.Consumer;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.JOptionPane;


/**
 *
 * @author Acer
 */
public class TrangChuDV extends javax.swing.JFrame implements TrangChuDVController{

    // Khai báo một thể hiện của PhongDao
    private PhongDao phongDao = new PhongDaoImpl();
    /**
     * Creates new form TrangChuDV
     */
    public TrangChuDV() {
        initComponents();
        openFullScreen();
        anh();
    }
        int chieungang = 305;
    int chieudai = 704;
    
    private void openFullScreen() {
         // Bỏ viềds (tuỳ chọn)
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocationRelativeTo(null); // Đặt giữa, thực ra không quan trọng
    }
    void OpenMenuBar(){
        new Thread(new Runnable() {
            @Override
            public void run() {
                Open.setVisible(false);
                for (int i=0; i<chieungang; i++){
                    pnlMenuBar.setSize(i,chieudai);
                    try {
                        //mở từ từ
                        Thread.sleep(1);
                    } catch (InterruptedException ex) {
                        Logger.getLogger(TrangChu.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
            }
        }).start();
    }
    
    void CloseOpenBar(){
        new Thread(new Runnable() {
            @Override
            public void run() {
                Open.setVisible(true);
                for (int i=chieungang; i>0; i--){
                    pnlMenuBar.setSize(i,chieudai);
                    try {
                        //mở từ từ
                        Thread.sleep(1);
                    } catch (InterruptedException ex) {
                        Logger.getLogger(TrangChu.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
            }
        }).start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        pnlMenuBar = new javax.swing.JPanel();
        btnTrangChu = new javax.swing.JLabel();
        btnDangXuat = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        btnDoiMK = new javax.swing.JLabel();
        btnDichV = new javax.swing.JLabel();
        bntChat = new javax.swing.JLabel();
        Open = new javax.swing.JLabel();
        KhungTrang = new javax.swing.JPanel();
        jpnTrangChu = new javax.swing.JPanel();
        jpnKhungAnh = new javax.swing.JPanel();
        txtTen = new javax.swing.JLabel();
        Anh = new javax.swing.JLabel();
        btnDichV1 = new javax.swing.JLabel();
        bntChat1 = new javax.swing.JLabel();
        jpnDMK = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtTenDN = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnLMDMK = new javax.swing.JButton();
        btnLuuDMK = new javax.swing.JButton();
        txtMKHT = new javax.swing.JPasswordField();
        txtMKM = new javax.swing.JPasswordField();
        txtXNMKM = new javax.swing.JPasswordField();
        jpnDichVu = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        pnlTang = new javax.swing.JPanel();
        pnlChat = new javax.swing.JPanel();
        Tieude = new javax.swing.JPanel();
        jpnTDTrangChu = new javax.swing.JPanel();
        txtTrangChu = new javax.swing.JLabel();
        jpnTDDMK = new javax.swing.JPanel();
        txtDMK = new javax.swing.JLabel();
        jpnTDDichVu = new javax.swing.JPanel();
        txtDMK1 = new javax.swing.JLabel();
        pnlTDChat = new javax.swing.JPanel();
        txtDMK4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setMinimumSize(new java.awt.Dimension(1200, 700));

        pnlMenuBar.setBackground(new java.awt.Color(204, 204, 204));
        pnlMenuBar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        pnlMenuBar.setMinimumSize(new java.awt.Dimension(305, 699));

        btnTrangChu.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnTrangChu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnTrangChu.setText("Trang Chủ");
        btnTrangChu.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnTrangChu.setMinimumSize(new java.awt.Dimension(291, 40));
        btnTrangChu.setPreferredSize(new java.awt.Dimension(91, 40));
        btnTrangChu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnTrangChuMouseClicked(evt);
            }
        });

        btnDangXuat.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnDangXuat.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnDangXuat.setText("Đăng xuất");
        btnDangXuat.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnDangXuat.setMinimumSize(new java.awt.Dimension(291, 40));
        btnDangXuat.setPreferredSize(new java.awt.Dimension(70, 40));
        btnDangXuat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDangXuatMouseClicked(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/dong.png"))); // NOI18N
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });

        btnDoiMK.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnDoiMK.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnDoiMK.setText("Đổi mật khẩu");
        btnDoiMK.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnDoiMK.setMinimumSize(new java.awt.Dimension(291, 40));
        btnDoiMK.setPreferredSize(new java.awt.Dimension(91, 40));
        btnDoiMK.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDoiMKMouseClicked(evt);
            }
        });

        btnDichV.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnDichV.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnDichV.setText("Dịch Vụ");
        btnDichV.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnDichV.setMinimumSize(new java.awt.Dimension(291, 40));
        btnDichV.setPreferredSize(new java.awt.Dimension(91, 40));
        btnDichV.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDichVMouseClicked(evt);
            }
        });

        bntChat.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        bntChat.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bntChat.setText("Trò Chuyện");
        bntChat.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        bntChat.setMinimumSize(new java.awt.Dimension(291, 40));
        bntChat.setPreferredSize(new java.awt.Dimension(91, 40));
        bntChat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bntChatMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout pnlMenuBarLayout = new javax.swing.GroupLayout(pnlMenuBar);
        pnlMenuBar.setLayout(pnlMenuBarLayout);
        pnlMenuBarLayout.setHorizontalGroup(
            pnlMenuBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMenuBarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlMenuBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlMenuBarLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnDangXuat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnTrangChu, javax.swing.GroupLayout.DEFAULT_SIZE, 291, Short.MAX_VALUE)
                    .addComponent(btnDichV, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnDoiMK, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bntChat, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        pnlMenuBarLayout.setVerticalGroup(
            pnlMenuBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlMenuBarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnTrangChu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(btnDichV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bntChat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 402, Short.MAX_VALUE)
                .addComponent(btnDoiMK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnDangXuat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );

        Open.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        Open.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Open.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/mo.png"))); // NOI18N
        Open.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                OpenMouseClicked(evt);
            }
        });

        KhungTrang.setBackground(new java.awt.Color(255, 255, 255));
        KhungTrang.setLayout(new java.awt.CardLayout());

        jpnTrangChu.setBackground(new java.awt.Color(255, 255, 255));

        jpnKhungAnh.setBackground(new java.awt.Color(255, 255, 255));

        txtTen.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txtTen.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtTen.setText("Nguyễn Văn Bách");

        Anh.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Anh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Logo.png"))); // NOI18N
        Anh.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204), 2));
        Anh.setPreferredSize(new java.awt.Dimension(200, 250));

        btnDichV1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnDichV1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnDichV1.setText("Dịch Vụ");
        btnDichV1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnDichV1.setMinimumSize(new java.awt.Dimension(291, 40));
        btnDichV1.setPreferredSize(new java.awt.Dimension(91, 40));
        btnDichV1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDichV1MouseClicked(evt);
            }
        });

        bntChat1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        bntChat1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bntChat1.setText("Trò Chuyện");
        bntChat1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        bntChat1.setMinimumSize(new java.awt.Dimension(291, 40));
        bntChat1.setPreferredSize(new java.awt.Dimension(91, 40));
        bntChat1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bntChat1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jpnTrangChuLayout = new javax.swing.GroupLayout(jpnTrangChu);
        jpnTrangChu.setLayout(jpnTrangChuLayout);
        jpnTrangChuLayout.setHorizontalGroup(
            jpnTrangChuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnTrangChuLayout.createSequentialGroup()
                .addGap(206, 206, 206)
                .addComponent(jpnKhungAnh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jpnTrangChuLayout.createSequentialGroup()
                .addGap(494, 494, 494)
                .addGroup(jpnTrangChuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtTen, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Anh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(500, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnTrangChuLayout.createSequentialGroup()
                .addContainerGap(438, Short.MAX_VALUE)
                .addGroup(jpnTrangChuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(bntChat1, javax.swing.GroupLayout.DEFAULT_SIZE, 291, Short.MAX_VALUE)
                    .addComponent(btnDichV1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(465, 465, 465))
        );
        jpnTrangChuLayout.setVerticalGroup(
            jpnTrangChuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnTrangChuLayout.createSequentialGroup()
                .addGap(85, 85, 85)
                .addComponent(Anh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtTen)
                .addGap(18, 18, 18)
                .addComponent(btnDichV1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addComponent(bntChat1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpnKhungAnh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(149, 149, 149))
        );

        KhungTrang.add(jpnTrangChu, "card2");

        jpnDMK.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setText("Tên đăng nhập:");

        txtTenDN.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        txtTenDN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTenDNActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel3.setText("Mật khẩu hiện tại:");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel4.setText("Mật khẩu mới:");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel5.setText("Xác nhận mật khẩu mới:");

        btnLMDMK.setBackground(new java.awt.Color(204, 204, 204));
        btnLMDMK.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnLMDMK.setText("Lưu");
        btnLMDMK.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        btnLMDMK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLMDMKActionPerformed(evt);
            }
        });

        btnLuuDMK.setBackground(new java.awt.Color(204, 204, 204));
        btnLuuDMK.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnLuuDMK.setText("Làm mới");
        btnLuuDMK.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        btnLuuDMK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLuuDMKActionPerformed(evt);
            }
        });

        txtMKHT.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        txtMKHT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMKHTActionPerformed(evt);
            }
        });

        txtMKM.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        txtMKM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMKMActionPerformed(evt);
            }
        });

        txtXNMKM.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        txtXNMKM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtXNMKMActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpnDMKLayout = new javax.swing.GroupLayout(jpnDMK);
        jpnDMK.setLayout(jpnDMKLayout);
        jpnDMKLayout.setHorizontalGroup(
            jpnDMKLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnDMKLayout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addGroup(jpnDMKLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jpnDMKLayout.createSequentialGroup()
                        .addComponent(btnLuuDMK, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(45, 45, 45)
                        .addComponent(btnLMDMK, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpnDMKLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel5)
                        .addComponent(jLabel2)
                        .addComponent(txtTenDN, javax.swing.GroupLayout.DEFAULT_SIZE, 1041, Short.MAX_VALUE)
                        .addComponent(jLabel3)
                        .addComponent(jLabel4)
                        .addComponent(txtMKHT)
                        .addComponent(txtMKM, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(txtXNMKM)))
                .addContainerGap(79, Short.MAX_VALUE))
        );
        jpnDMKLayout.setVerticalGroup(
            jpnDMKLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnDMKLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtTenDN, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtMKHT, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtMKM, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtXNMKM, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 82, Short.MAX_VALUE)
                .addGroup(jpnDMKLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLMDMK, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLuuDMK, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41))
        );

        KhungTrang.add(jpnDMK, "card3");

        jpnDichVu.setBackground(new java.awt.Color(255, 255, 255));

        jScrollPane1.setBorder(null);

        pnlTang.setBackground(new java.awt.Color(255, 255, 255));
        pnlTang.setLayout(new java.awt.GridLayout(0, 6, 5, 5));
        jScrollPane1.setViewportView(pnlTang);

        javax.swing.GroupLayout jpnDichVuLayout = new javax.swing.GroupLayout(jpnDichVu);
        jpnDichVu.setLayout(jpnDichVuLayout);
        jpnDichVuLayout.setHorizontalGroup(
            jpnDichVuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1194, Short.MAX_VALUE)
        );
        jpnDichVuLayout.setVerticalGroup(
            jpnDichVuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 653, Short.MAX_VALUE)
        );

        KhungTrang.add(jpnDichVu, "card4");

        javax.swing.GroupLayout pnlChatLayout = new javax.swing.GroupLayout(pnlChat);
        pnlChat.setLayout(pnlChatLayout);
        pnlChatLayout.setHorizontalGroup(
            pnlChatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1194, Short.MAX_VALUE)
        );
        pnlChatLayout.setVerticalGroup(
            pnlChatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 653, Short.MAX_VALUE)
        );

        KhungTrang.add(pnlChat, "card5");

        Tieude.setBackground(new java.awt.Color(255, 255, 255));
        Tieude.setLayout(new java.awt.CardLayout());

        jpnTDTrangChu.setBackground(new java.awt.Color(204, 204, 204));

        txtTrangChu.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        txtTrangChu.setText("Trang Chủ");

        javax.swing.GroupLayout jpnTDTrangChuLayout = new javax.swing.GroupLayout(jpnTDTrangChu);
        jpnTDTrangChu.setLayout(jpnTDTrangChuLayout);
        jpnTDTrangChuLayout.setHorizontalGroup(
            jpnTDTrangChuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtTrangChu, javax.swing.GroupLayout.DEFAULT_SIZE, 1030, Short.MAX_VALUE)
        );
        jpnTDTrangChuLayout.setVerticalGroup(
            jpnTDTrangChuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnTDTrangChuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtTrangChu, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                .addContainerGap())
        );

        Tieude.add(jpnTDTrangChu, "card2");

        jpnTDDMK.setBackground(new java.awt.Color(204, 204, 204));

        txtDMK.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        txtDMK.setText("Đổi Mật Khẩu");

        javax.swing.GroupLayout jpnTDDMKLayout = new javax.swing.GroupLayout(jpnTDDMK);
        jpnTDDMK.setLayout(jpnTDDMKLayout);
        jpnTDDMKLayout.setHorizontalGroup(
            jpnTDDMKLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtDMK, javax.swing.GroupLayout.DEFAULT_SIZE, 1030, Short.MAX_VALUE)
        );
        jpnTDDMKLayout.setVerticalGroup(
            jpnTDDMKLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnTDDMKLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtDMK, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                .addContainerGap())
        );

        Tieude.add(jpnTDDMK, "card2");

        jpnTDDichVu.setBackground(new java.awt.Color(204, 204, 204));

        txtDMK1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        txtDMK1.setText("Dịch Vụ");

        javax.swing.GroupLayout jpnTDDichVuLayout = new javax.swing.GroupLayout(jpnTDDichVu);
        jpnTDDichVu.setLayout(jpnTDDichVuLayout);
        jpnTDDichVuLayout.setHorizontalGroup(
            jpnTDDichVuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtDMK1, javax.swing.GroupLayout.DEFAULT_SIZE, 1030, Short.MAX_VALUE)
        );
        jpnTDDichVuLayout.setVerticalGroup(
            jpnTDDichVuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnTDDichVuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtDMK1, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                .addContainerGap())
        );

        Tieude.add(jpnTDDichVu, "card2");

        pnlTDChat.setBackground(new java.awt.Color(204, 204, 204));

        txtDMK4.setBackground(new java.awt.Color(204, 204, 204));
        txtDMK4.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        txtDMK4.setText("Trò Chuyện");

        javax.swing.GroupLayout pnlTDChatLayout = new javax.swing.GroupLayout(pnlTDChat);
        pnlTDChat.setLayout(pnlTDChatLayout);
        pnlTDChatLayout.setHorizontalGroup(
            pnlTDChatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtDMK4, javax.swing.GroupLayout.DEFAULT_SIZE, 1030, Short.MAX_VALUE)
        );
        pnlTDChatLayout.setVerticalGroup(
            pnlTDChatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTDChatLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtDMK4, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                .addContainerGap())
        );

        Tieude.add(pnlTDChat, "card6");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(pnlMenuBar, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(KhungTrang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Tieude, javax.swing.GroupLayout.PREFERRED_SIZE, 1030, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(78, 78, 78))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(Open, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlMenuBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Tieude, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Open))
                .addGap(0, 0, 0)
                .addComponent(KhungTrang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTrangChuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTrangChuMouseClicked
        // TODO add your handling code here:
        jpnTrangChu.setVisible(true);
        jpnTDTrangChu.setVisible(true);
        jpnDMK.setVisible(false);
        jpnTDDMK.setVisible(false);
        jpnDichVu.setVisible(false);
        jpnTDDichVu.setVisible(false);
         pnlChat.setVisible(false);
        Open.setVisible(true);
    }//GEN-LAST:event_btnTrangChuMouseClicked

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        // TODO add your handling code here:
        CloseOpenBar();
    }//GEN-LAST:event_jLabel1MouseClicked

    private void btnDoiMKMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDoiMKMouseClicked
        // TODO add your handling code here:
        jpnTrangChu.setVisible(false);
        jpnTDTrangChu.setVisible(false);
        jpnDMK.setVisible(true);
        jpnTDDMK.setVisible(true);
        jpnDichVu.setVisible(false);
        jpnTDDichVu.setVisible(false);
         pnlChat.setVisible(false);
        Open.setVisible(true);
    }//GEN-LAST:event_btnDoiMKMouseClicked

    private void btnDichVMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDichVMouseClicked
        // TODO add your handling code here:
        jpnTrangChu.setVisible(false);
        jpnTDTrangChu.setVisible(false);
        jpnDMK.setVisible(false);
        jpnTDDMK.setVisible(false);
        jpnDichVu.setVisible(true);
        jpnTDDichVu.setVisible(true);
         pnlChat.setVisible(false);
        Open.setVisible(true);
    }//GEN-LAST:event_btnDichVMouseClicked

    private void OpenMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_OpenMouseClicked
        // TODO add your handling code here:
        OpenMenuBar();
    }//GEN-LAST:event_OpenMouseClicked

    private void txtTenDNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTenDNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTenDNActionPerformed

    private void btnLuuDMKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLuuDMKActionPerformed
        // TODO add your handling code here:
        clearDMK();
    }//GEN-LAST:event_btnLuuDMKActionPerformed

    private void txtMKHTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMKHTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMKHTActionPerformed

    private void txtMKMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMKMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMKMActionPerformed

    private void txtXNMKMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtXNMKMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtXNMKMActionPerformed

    private void btnLMDMKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLMDMKActionPerformed
        // TODO add your handling code here:
        UpdateMK();
    }//GEN-LAST:event_btnLMDMKActionPerformed

    private void btnDangXuatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDangXuatMouseClicked
        // TODO add your handling code here:
        DX();
    }//GEN-LAST:event_btnDangXuatMouseClicked

    private void btnDichV1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDichV1MouseClicked
        // TODO add your handling code here:
                jpnTrangChu.setVisible(false);
        jpnTDTrangChu.setVisible(false);
        jpnDMK.setVisible(false);
        jpnTDDMK.setVisible(false);
        jpnDichVu.setVisible(true);
        jpnTDDichVu.setVisible(true);
        Open.setVisible(true);
         pnlChat.setVisible(false);
        loadRoomsByStatus();
        
    }//GEN-LAST:event_btnDichV1MouseClicked

    private void bntChatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bntChatMouseClicked
        jpnTrangChu.setVisible(false);
        jpnTDTrangChu.setVisible(false);
        jpnDMK.setVisible(false);
        jpnTDDMK.setVisible(false);
        jpnDichVu.setVisible(false);
        jpnTDDichVu.setVisible(false);
        Open.setVisible(true);
        pnlChat.setVisible(true);
        pnlTDChat.setVisible(true);
    }//GEN-LAST:event_bntChatMouseClicked

    private void bntChat1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bntChat1MouseClicked
        jpnTrangChu.setVisible(false);
        jpnTDTrangChu.setVisible(false);
        jpnDMK.setVisible(false);
        jpnTDDMK.setVisible(false);
        jpnDichVu.setVisible(false);
        jpnTDDichVu.setVisible(false);
        Open.setVisible(true);
        pnlChat.setVisible(true);
        pnlTDChat.setVisible(true);
    }//GEN-LAST:event_bntChat1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TrangChuDV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TrangChuDV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TrangChuDV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TrangChuDV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TrangChuDV().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Anh;
    private javax.swing.JPanel KhungTrang;
    private javax.swing.JLabel Open;
    private javax.swing.JPanel Tieude;
    private javax.swing.JLabel bntChat;
    private javax.swing.JLabel bntChat1;
    private javax.swing.JLabel btnDangXuat;
    private javax.swing.JLabel btnDichV;
    private javax.swing.JLabel btnDichV1;
    private javax.swing.JLabel btnDoiMK;
    private javax.swing.JButton btnLMDMK;
    private javax.swing.JButton btnLuuDMK;
    private javax.swing.JLabel btnTrangChu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel jpnDMK;
    private javax.swing.JPanel jpnDichVu;
    private javax.swing.JPanel jpnKhungAnh;
    private javax.swing.JPanel jpnTDDMK;
    private javax.swing.JPanel jpnTDDichVu;
    private javax.swing.JPanel jpnTDTrangChu;
    private javax.swing.JPanel jpnTrangChu;
    private javax.swing.JPanel pnlChat;
    private javax.swing.JPanel pnlMenuBar;
    private javax.swing.JPanel pnlTDChat;
    private javax.swing.JPanel pnlTang;
    private javax.swing.JLabel txtDMK;
    private javax.swing.JLabel txtDMK1;
    private javax.swing.JLabel txtDMK4;
    private javax.swing.JPasswordField txtMKHT;
    private javax.swing.JPasswordField txtMKM;
    private javax.swing.JLabel txtTen;
    private javax.swing.JTextField txtTenDN;
    private javax.swing.JLabel txtTrangChu;
    private javax.swing.JPasswordField txtXNMKM;
    // End of variables declaration//GEN-END:variables
@Override
public void open() {
    this.setLocationRelativeTo(null);
}
    String folder = "images";
    Consumer<File> fileChanged;

    public String getFolder() {
        return folder;
    }

    public void setFolder(String folder) {
        this.folder = folder;
    }
    
    public void setIcon(String icon) {
        Anh.setText("");
        Anh.setToolTipText(icon);
        XIcon.setIcon(Anh, new File(this.folder, icon));
    }
     
    public String getIcon() {
        return Anh.getToolTipText();
    }
@Override
public void anh(){
    this.setIconImage(XIcon.getIcon("Logo.png").getImage());
    if (XAuth.user != null) {
            txtTen.setText(XAuth.user.getHoVaTen());
            // Đảm bảo ảnh của người dùng đang đăng nhập cũng được tải đúng cách
            // Giả sử ảnh của user đăng nhập cũng nằm trong folder "images"
            if (XAuth.user.getAnh() != null && !XAuth.user.getAnh().isEmpty()) {
                XIcon.setIcon(Anh, new File(folder, XAuth.user.getAnh()));
            } else {
                XIcon.setIcon(Anh, "/Icon/Logo.png"); // Ảnh mặc định nếu không có
            }
        }
}

private void loadCards() {
    LoaiPhongDao dao = new LoaiPhongDaoImpl();
    List<LoaiPhong> LP = dao.findAll();

    pnlTang.removeAll();
    LP.forEach(card -> {
        pnlTang.add(this.createButton(card));
    });
}
// Phương thức mới để tải và hiển thị các phòng có trạng thái "Đang dọn dẹp" hoặc "Đang có dịch vụ"
private void loadRoomsByStatus() {
    pnlTang.removeAll(); // Xóa các nút phòng cũ

    List<Phong> allRooms = phongDao.findAll(); // Lấy tất cả các phòng
    for (Phong room : allRooms) {
        String status = room.getTrangThai();
        if ("Đang dọn dẹp".equals(status) || "Đang có dịch vụ".equals(status)) {
            pnlTang.add(createRoomButton(room)); // Thêm nút cho các phòng phù hợp
        }
    }
    pnlTang.revalidate(); // Cập nhật lại giao diện
    pnlTang.repaint(); // Vẽ lại giao diện
}

// Phương thức mới để tạo nút cho từng đối tượng Phong
private JButton createRoomButton(Phong phong) {
   JButton btnRoom = new JButton();
    // Hiển thị số phòng và trạng thái trên các dòng riêng biệt bằng HTML
    btnRoom.setText(String.format("<html>Phòng: %s<br>Trạng thái: %s</html>", phong.getSoPhong(), phong.getTrangThai()));
    btnRoom.setPreferredSize(new Dimension(150, 80)); // Đặt kích thước tương tự các nút khác
    btnRoom.setActionCommand(String.valueOf(phong.getId())); // Đặt ID phòng làm action command
    
    // Đặt màu nền của button thành màu vàng
    btnRoom.setBackground(java.awt.Color.YELLOW);
    btnRoom.addActionListener((ActionEvent e) -> {
        int roomId = Integer.parseInt(e.getActionCommand());
        System.out.println("Đã nhấp phòng với ID: " + roomId);

        // Hiển thị thông báo xác nhận
        int confirmResult = JOptionPane.showConfirmDialog(
            this, // Parent component
            "Bạn có muốn đổi trạng thái phòng " + phong.getSoPhong() + " sang 'Trống' không?",
            "Xác nhận đổi trạng thái",
            JOptionPane.YES_NO_OPTION,
            JOptionPane.QUESTION_MESSAGE
        );

        if (confirmResult == JOptionPane.YES_OPTION) {
            // Người dùng đã xác nhận muốn đổi trạng thái
            // Thêm logic để cập nhật trạng thái phòng ở đây
            // Ví dụ:
            PhongDao phongDao = new PhongDaoImpl(); // Khởi tạo lại hoặc sử dụng thể hiện đã có
            Phong phongCanCapNhat = phongDao.findById(roomId); // Lấy đối tượng phòng từ DB
            if (phongCanCapNhat != null) {
                phongCanCapNhat.setTrangThai("Trống"); // Đặt trạng thái mới
                phongDao.update(phongCanCapNhat); // Cập nhật vào cơ sở dữ liệu
                JOptionPane.showMessageDialog(this, "Đã đổi trạng thái phòng " + phong.getSoPhong() + " thành 'Trống'.");
                loadRoomsByStatus(); // Tải lại danh sách phòng để cập nhật giao diện
            } else {
                JOptionPane.showMessageDialog(this, "Không tìm thấy phòng để cập nhật.", "Lỗi", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            // Người dùng chọn "Không" hoặc đóng hộp thoại
            System.out.println("Người dùng đã hủy thao tác đổi trạng thái.");
        }
    });
    return btnRoom;
}

private JButton createButton(LoaiPhong lp) {
    JButton btnCard = new JButton();
    btnCard.setText(String.format("%s", lp.getTenLoaiPhong()));
    btnCard.setPreferredSize(new Dimension(150, 80));
    btnCard.setActionCommand(String.valueOf(lp.getId()));
    btnCard.addActionListener((ActionEvent e) -> {
        int Id = Integer.parseInt(e.getActionCommand());
        System.out.println(Id);
    }); 
    return btnCard;
}
void UpdateMK(){
    String username = txtTenDN.getText().trim();
    String password = new String(txtMKHT.getPassword());
    String MKM = new String(txtMKM.getPassword());
    String MKMM = new String(txtXNMKM.getPassword());

NguoiDungDao dao = new NguoiDungDaoImpl();
if (username.isEmpty()) {
    XDialog.alert("Chưa nhập tên đăng nhập\n");
    return;
}
if (password.isEmpty()) {
    XDialog.alert("Chưa nhập mật khẩu cũ\n");
    return;
}
if (MKM.isEmpty()) {
    XDialog.alert("Chưa nhập mật khẩu mới\n");
    return;
}
if (!MKM.equals(MKMM)) {
    XDialog.alert("2 mật khẩu đang khác nhau\n");
    return;
}

// Sau khi kiểm tra xong đầu vào mới truy vấn user
NguoiDung user = dao.findById(username); // ví dụ, tuỳ bạn đặt tên hàm

if (user == null) {
    XDialog.alert("Sai tên đăng nhập!");
    return;
}
if (!password.equals(user.getMatKhau())) {
    XDialog.alert("Sai mật khẩu hiện tại!");
    return;
}
if (MKM.equals(user.getMatKhau())) {
    XDialog.alert("Mật khẩu mới không được giống mật khẩu cũ!");
    return;
}

// Đến đây thì hợp lệ -> cập nhật mật khẩu
user.setMatKhau(MKM);
dao.update(user);
XDialog.alert("Đổi mật khẩu thành công!");
clearDMK();
}

void clearDMK(){
  txtTenDN.setText("");
txtMKHT.setText("");
txtMKM.setText("");
txtXNMKM.setText("");  
}

void DX(){
    this.dispose();
    this.showDX(this);
}
}
